#!/usr/bin/env python3
"""Generate hooks/scripts/INDEX.md from hooks.json and the scripts/ folder.

Produces two views:
  - By event: one section per event in hooks.json order, listing hook scripts
    with their matcher and one-line purpose.
  - By purpose (family folder): one section per top-level folder under
    hooks/scripts/, listing the scripts it owns.

Usage:
  python3 scripts/render-hooks-index.py
  # Writes plugins/panther-ivy-plugin/hooks/scripts/INDEX.md
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


PLUGIN_ROOT = Path(__file__).resolve().parent.parent
HOOKS_JSON = PLUGIN_ROOT / "hooks" / "hooks.json"
SCRIPTS_DIR = PLUGIN_ROOT / "hooks" / "scripts"
OUTPUT = SCRIPTS_DIR / "INDEX.md"

_ATTRIBUTION = "_Auto-generated by `scripts/render-hooks-index.py`. Re-run after any hook change._"


def _extract_docstring(script_path: Path) -> Optional[str]:
    """Return the first line of the module docstring, or None if absent."""
    try:
        source = script_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (SyntaxError, OSError):
        return None
    if not (tree.body and isinstance(tree.body[0], ast.Expr)):
        return None
    expr = tree.body[0].value
    if not isinstance(expr, ast.Constant) or not isinstance(expr.value, str):
        return None
    first_line = expr.value.strip().splitlines()[0].strip()
    return first_line if first_line else None


def _command_to_script_path(command: str) -> Tuple[Optional[Path], str]:
    """Parse a hooks.json command string into (absolute_path, display_name).

    Returns (None, display_name) when the path cannot be resolved on disk.
    """
    # Normalise the command: strip leading 'python3 ' and trailing args
    cmd = command.strip()
    cmd = re.sub(r"^python3\s+", "", cmd)
    # Replace ${CLAUDE_PLUGIN_ROOT} with PLUGIN_ROOT
    cmd = cmd.replace("${CLAUDE_PLUGIN_ROOT}", str(PLUGIN_ROOT))
    # Split off trailing args (e.g. '--event PreToolUse', '--id g2')
    parts = cmd.split()
    script_str = parts[0]
    extra_args = " ".join(parts[1:])
    script_path = Path(script_str)
    display = script_path.relative_to(SCRIPTS_DIR).as_posix() if script_path.is_relative_to(SCRIPTS_DIR) else script_path.name
    if extra_args:
        display = f"{display} {extra_args}"
    return (script_path if script_path.exists() else None, display)


def _one_line_purpose(script_path: Optional[Path], display: str) -> str:
    """Return one-line purpose: first docstring line or basename fallback."""
    if script_path is not None:
        doc = _extract_docstring(script_path)
        if doc:
            # Strip common event-name hook prefixes, including backtick-quoted
            # matcher variants (single or double backtick, rst-style):
            #   "PostToolUse hook: "
            #   "PostToolUse hook on the `Skill` matcher: "
            #   "PostToolUse hook on the ``Skill`` matcher: "
            doc = re.sub(
                r"^(Pre|Post|Session|Stop|SubagentStart|UserPromptSubmit|Notification|PreCompact|PermissionRequest)\w*"
                r"(\s+hook(?:\s+on\s+the\s+`{1,2}[^`]+`{1,2}\s+matcher)?)?\s*:\s*",
                "",
                doc,
                flags=re.IGNORECASE,
            )
            # Strip trailing punctuation that signals the sentence was split
            # across multiple docstring lines (comma, colon, semicolon).
            doc = doc.rstrip(".,:")
            return doc
    return display.split("/")[-1].replace(".py", "")


def _load_hooks() -> Dict[str, Any]:
    data = json.loads(HOOKS_JSON.read_text(encoding="utf-8"))
    return data.get("hooks", {})


def _iter_event_hooks(hooks: Dict[str, Any]):
    """Yield (event, matcher, command) tuples in hooks.json order."""
    for event, matchers in hooks.items():
        for block in matchers:
            matcher = block.get("matcher", "")
            for hook in block.get("hooks", []):
                cmd = hook.get("command", "")
                if cmd:
                    yield event, matcher, cmd


def _family_of(display: str) -> str:
    """Return the top-level family folder name from a display path."""
    parts = display.split(" ")[0].split("/")
    if len(parts) >= 2:
        return parts[0]
    return "."


def _build_by_event(hooks: Dict[str, Any]) -> List[str]:
    lines: List[str] = []
    for event, matchers in hooks.items():
        lines.append(f"### {event}")
        for block in matchers:
            matcher = block.get("matcher", "")
            matcher_label = f"`{matcher}`" if matcher else "(no matcher)"
            for hook in block.get("hooks", []):
                cmd = hook.get("command", "")
                if not cmd:
                    continue
                path, display = _command_to_script_path(cmd)
                purpose = _one_line_purpose(path, display)
                lines.append(f"- [{display}]({display.split(' ')[0]}) — {matcher_label} — {purpose}")
        lines.append("")
    return lines


def _build_by_family(hooks: Dict[str, Any]) -> List[str]:
    """Build the by-purpose section, one sub-section per top-level family folder."""
    # Collect all scripts and their families
    family_map: Dict[str, List[Tuple[str, str]]] = {}

    for _event, _matcher, cmd in _iter_event_hooks(hooks):
        path, display = _command_to_script_path(cmd)
        fam = _family_of(display)
        purpose = _one_line_purpose(path, display)
        entry = (display, purpose)
        if entry not in family_map.get(fam, []):
            family_map.setdefault(fam, []).append(entry)

    lines: List[str] = []
    for fam in sorted(family_map):
        lines.append(f"### {fam}")
        seen = set()
        for display, purpose in family_map[fam]:
            if display not in seen:
                seen.add(display)
                script_part = display.split(" ")[0]
                lines.append(f"- [{display}]({script_part}) — {purpose}")
        lines.append("")
    return lines


def render(hooks: Dict[str, Any]) -> str:
    by_event = _build_by_event(hooks)
    by_family = _build_by_family(hooks)

    parts = [
        "# panther-ivy-plugin hooks/ index",
        "",
        _ATTRIBUTION,
        "",
        "## By event",
        "",
    ]
    parts.extend(by_event)
    parts.extend([
        "## By purpose (top-level family folder)",
        "",
    ])
    parts.extend(by_family)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render hooks/scripts/INDEX.md.")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="Output path")
    args = parser.parse_args()

    hooks = _load_hooks()
    content = render(hooks)
    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
