#!/usr/bin/env python3
"""PROJECT.md schema validation, load, and write.

PROJECT.md is the per-protocol rolled-up status view. It is a derived
artifact: never hand-edited, regenerated by render-project-md.py from
the workflow journal.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, FrozenSet

import yaml

_PROTOCOL_TESTING_DIR = "protocol-testing"
_PROJECT_MD_NAME = "PROJECT.md"


def resolve_protocol_dir(root: Path, protocol: str) -> Path:
    """Return the absolute path to ``<root>/protocol-testing/<protocol>/``.

    Centralised so render-project-md.py, the PostToolUse hook, the
    statusline segment, and the bootstrap migration all converge on the
    same path. ``protocol`` is taken verbatim from the workspace state
    (``active_group``) without further normalization.
    """
    return root / _PROTOCOL_TESTING_DIR / protocol


def resolve_project_md_path(protocol_dir: Path) -> Path:
    """Return the absolute path to ``<protocol_dir>/PROJECT.md``."""
    return protocol_dir / _PROJECT_MD_NAME


PROJECT_MD_KEYS: FrozenSet[str] = frozenset(
    {
        "protocol",
        "version",
        "mode",
        "phase",
        "journal_pointer",
        "last_verify",
        "rfc_sections_covered",
        "open_counterexamples",
        "last_iut_run",
        "deferred_layers",
    }
)

_VALID_MODES: FrozenSet[str] = frozenset({"scaffold", "refine", "experiment", "idle"})
_VALID_VERIFY_STATUS: FrozenSet[str] = frozenset({"SAT", "UNSAT", "NOT_RUN"})
_VALID_IUT_VERDICT: FrozenSet[str] = frozenset(
    {"NO_VIOLATION_FOUND", "NON_COMPLIANT", "TESTER_CRASH", "IUT_CRASH"}
)


class ProjectMdSchemaError(ValueError):
    """Raised when PROJECT.md frontmatter fails validation."""


def _validate(state: Dict[str, Any]) -> None:
    missing = PROJECT_MD_KEYS - state.keys()
    if missing:
        raise ProjectMdSchemaError(f"missing keys: {sorted(missing)}")
    extra = state.keys() - PROJECT_MD_KEYS
    if extra:
        raise ProjectMdSchemaError(f"unknown keys: {sorted(extra)}")
    if state["mode"] not in _VALID_MODES:
        raise ProjectMdSchemaError(
            f"mode must be one of {sorted(_VALID_MODES)}; got {state['mode']!r}"
        )
    if not isinstance(state["phase"], int) or not 0 <= state["phase"] <= 10:
        raise ProjectMdSchemaError(
            f"phase must be int in [0, 10]; got {state['phase']!r}"
        )
    lv = state["last_verify"]
    if not isinstance(lv, dict) or lv.get("status") not in _VALID_VERIFY_STATUS:
        raise ProjectMdSchemaError(
            f"last_verify.status must be one of {sorted(_VALID_VERIFY_STATUS)}; got {lv!r}"
        )
    iut = state["last_iut_run"]
    if iut is not None:
        if not isinstance(iut, dict) or iut.get("verdict") not in _VALID_IUT_VERDICT:
            raise ProjectMdSchemaError(
                f"last_iut_run.verdict must be one of {sorted(_VALID_IUT_VERDICT)} or null; got {iut!r}"
            )


def _split_frontmatter(text: str) -> str:
    """Return the YAML frontmatter block, raising on missing fences."""
    if not text.startswith("---\n"):
        raise ProjectMdSchemaError("PROJECT.md must start with YAML frontmatter")
    parts = text.split("---\n", 2)
    if len(parts) < 3:
        raise ProjectMdSchemaError("PROJECT.md frontmatter missing closing '---'")
    return parts[1]


def load_project_md(path: Path) -> Dict[str, Any]:
    """Load and validate a PROJECT.md file.

    Args:
        path: Path to the PROJECT.md file.

    Returns:
        Validated state dict with all PROJECT_MD_KEYS present.

    Raises:
        ProjectMdSchemaError: If frontmatter is missing, malformed, or fails schema.
    """
    text = Path(path).read_text()
    frontmatter = _split_frontmatter(text)
    state: Dict[str, Any] = yaml.safe_load(frontmatter) or {}
    _validate(state)
    return state


def write_project_md(path: Path, state: Dict[str, Any]) -> None:
    """Validate and write PROJECT.md frontmatter (no body).

    Args:
        path: Destination path; parent directory is created if missing.
        state: Schema-conformant state dict.

    Raises:
        ProjectMdSchemaError: If state fails validation.
    """
    _validate(state)
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(state, sort_keys=False, default_flow_style=False)
    target.write_text(f"---\n{body}---\n")
